@startuml
'https://plantuml.com/sequence-diagram

entity User {
    * id: number
    * email: string
    * password: string {hash}
    * first_name
    * last_name
    second_name
    * created_at: timestamp
    * modified_at: timestamp
}

entity UserHouse {
    * id: number
    * user_id: number
    * role_id: number
    * house_id: number
}

entity Roles {
    * id: number
    * name: string
    description: string
    * created_at: timestamp
}


entity Device {
    * id: number
    * type_id: number
    * house_id: number
    * serial_number: string
    * status: DeviceStatus
    description: string
    * created_at: timestamp
}

entity DeviceType {
    * id: number
    * type: string
}

entity House {
    * id: number
    * name: string
    address: string
    * created_at: timestamp
}

entity Module {
    * id: number
    * device_id: number
    * name: string
}

entity Telemetry {
    * id: number
    * device_id: number
    * metric: number
    * created_at: timestamp
}

enum DeviceStatus {
    active
    inactive
}

UserHouse }|-- User
UserHouse }|-- House
UserHouse }|-- Roles


Device }|-- House
Device }|-- DeviceType
Telemetry }|-- Device
Module }|-- Device
Device --> DeviceStatus

@enduml