openapi: 3.1.0
info:
  title: Tepliy Dom API - OpenAPI 3.1.0
  description: Tepliy Dom API - OpenAPI 3.1.0
  version: 1.0.0
servers:
  - url: 'https://tepliydom.com/api/'
paths:
  /devices:
    post:
      tags:
        - devices management service
      summary: Add new device
      operationId: createDevice
      requestBody:
        description: description
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Device'
        required: true
      responses:
        '200':
          description: description
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
        '400':
          description: Invalid input
        '422':
          description: Validation exception
    get:
      tags:
        - devices management service
      summary: Get list of devices
      operationId: getDeviceList
      responses:
        '200':
          description: sucessful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Device'
        '500':
          description: Internal service error
  /devices/command:
    post:
      tags:
        - devices management service
      summary: Run device command
      operationId: runDeviceCommand
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceCommand'
        '400':
          description: Invalid input
        '422':
          description: Validation exception



components:
  schemas:
    Device:
      required:
        - id
        - type_id
        - house_id
        - serial_number
        - status
        - created_at
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        type_id:
          type: integer
          format: int64
          example: 1
        house_id:
          type: integer
          format: int64
          example: 2
        serial_number:
          type: string
          example: AC11110111
        status:
          type: string
          description: Device Status
          example: active
          enum:
            - active
            - inactive
        description:
          type: string
          example: description
        created_at:
          type: string
          format: date-time
    DeviceCommand:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        device_id:
          type: integer
          format: int64
          example: 123
        command:
          type: string
          description: Device Command
          example: on
          enum:
            - on
            - off
